version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"         # Доступ через http://localhost:8081
    environment:
      PMA_HOST: db        # Имя mysql-сервиса из compose
      PMA_USER: myuser    # Пользователь для входа
      PMA_PASSWORD: mypassword # Пароль для входа
    depends_on:
      - db

volumes:
  mysql_data:
